// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwmcnxujhhvxrserqjrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3bWNueHVqaGh2eHJzZXJxanJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4MzY3MTYsImV4cCI6MjA4NjQxMjcxNn0.Kl5-uMnLGbwzCqKaH9WUDDQpX_2ASK2781bNNDpBL-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});